server:
  listen: 4002
  server_name: localhost
  root: www


  location:
    - path: "/"
    - root:   www
    - cgi: on
    - upload: on
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - index:  [index.html, index.htm]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - proxy_read_time_out: 4s

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST, GET]

server:
  listen: 6981
  server_name: localhost
  root: www
  location:
    - path: "/dsdsd"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]
    - redirect: ["index.html"]
    - upload_path: uploads

