server:
  listen: 2600
  server_name: localhost
  root: www

 
  location:
    - path: "/"
    - root:   www
    - cgi: on
    - upload: on
    - php: [.php, /usr/bin/php-cgi]
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - index:  [index.html, index.htm]
    - cgi_path: [.py, /user/bin/python3]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST, GET]

server:
  listen: 6981
  server_name: localhost
  root: www
  location:
    - path: "/dsdsd"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  # location:
  #   - path: "/cgi"
  #   - root: /Users/woumecht/Desktop/http2/cgi-bin
  #   - methods: [GET, POST]
  #   - upload: on
  #   - index: cgi-bin/index.sh
  #   - py: [.py, /user/bin/python3]
  #   - php: [.php, /usr/bin/php-cgi]
  #   - sh: [.sh, /bin/bash]


  location:
    - path: "/"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]
    - redirect: ["index.html"]
    - upload_path: uploads

