server:
  listen: 5001
  host: 127.0.0.1
  root: www/
  client_max_body_size: 2g
  error_pages: 403 www/error/403.html

  location:
    - path: "/"
    - root:   www
    - upload: on  
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - index:  [index.html]
    - cgi_path: [.py, /usr/bin/python3]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - cgi_path: [.sh, /usr/bin/bash]
    - proxy_read_time_out: 5s

server:
  listen: 5002
  host: 127.0.0.1
  root: www/
  client_max_body_size: 2g
  error_pages: 403 www/error/403.html

  location:
    - path: "/uploads"
    - root:   www 
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - proxy_read_time_out: 5s

server:
  listen: 5003
  host: 127.0.0.1
  root: www/
  client_max_body_size: 2g
  error_pages: 403 www/error/403.html

  location:
    - path: "/cgi-bin"
    - root: www
    - methods: [GET, POST]
    - upload: on
    - autoindex: on
    - cgi_path: [.py, /usr/bin/python3]
    - cgi_path: [.sh, /usr/bin/bash]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - proxy_read_time_out: 5s

server:
  listen: 5003
  server_name: wik.com
  host: 0.0.0.0
  root: www/
  client_max_body_size: 2g
  error_pages: 403 www/error/403.html

  location:
    - path: "/"
    - root:   www
    - upload: on
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - index:  [index.html, test.php]
    - cgi_path: [.py, /usr/bin/python3]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - cgi_path: [.sh, /usr/bin/bash]
    - proxy_read_time_out: 5s