server:
  listen: 6161
  server_name: localhost
  root: www


  location:
    - path: "/"
    - root:   www
    - cgi: on
    - upload: on
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - index:  [index.html, index.htm]
    - cgi_path: [.py, /user/bin/python3]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST, GET]

server:
  listen: 6981
  server_name: localhost
  root: www
  location:
    - path: "/dsdsd"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]
    - redirect: ["index.html"]
    - upload_path: uploads

