server:
  listen: 8081
  server_name: localhost
  root: www
  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on 
    - methods: [GET, POST]
    - index:  [index.html, index.htm]