server:
  listen: 4002
  server_name: localhost
  root: www
  location:
    - path: "/"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST]
    - index:  [index.html, index.htm]

server:
  listen: 2222
  server_name: localhost
  root: www
  location:
    - path: "/dsdsd"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]