server:
  listen: 2663
  server_name: localhost
  root: www
  client_max_body_size: 20m
  
  location:
    - path: "/"
    - root:   www
    - upload: on
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - index:  [index.html, index.htm]
    - cgi_path: [.py, /usr/bin/python3]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - cgi_path: [.sh, /usr/bin/sh]
    - proxy_read_time_out: 60s


  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST, GET]

  location:
    - path: "/cgi-bin"
    - root: www
    - methods: [GET, POST]
    - upload: off
    - index: cgi-bin/index.sh
    - cgi_path: [.py, /usr/bin/python3]
    - cgi_path: [.sh, /bin/sh]
    - cgi_path: [.php, /usr/bin/php-cgi]

server:
  listen: 6981
  server_name: localhost
  root: www
  location:
    - path: "/dsdsd"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/bootstrap"
    - root:   www
    - autoindex: on
    - methods: [GET, POST]
    - index:  [index.html, index.htm]

  location:
    - path: "/cgi-bin"
    - root: www
    - methods: [GET, POST]
    - upload: on
    - index: cgi-bin/index.sh
    - cgi_path: [.py, /usr/lib/python3]
    - cgi_path: [.sh, /bin/bash]
