server:
  listen: 5000
  host: 0.0.0.0
  root: www/
  client_max_body_size: 2g
  error_pages: 403 www/error/403.html

  location:
    - path: "/"
    - root:   www/
    - upload: on
    - autoindex: on
    - methods: [DELETE, POST, GET]
    - index:  [index.html, index.htm]
    - cgi_path: [.py, /usr/bin/python3]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - cgi_path: [.sh, /usr/bin/bash]
    - proxy_read_time_out: 10s

  location:
    - path: "/uploads"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST, GET]

  location:
    - path: "/uploads/shared"
    - root:   www
    - autoindex: on
    - methods: [DELETE, POST, GET]

  location:
    - path: "/cgi-bin"
    - root: www
    - methods: [GET, POST]
    - upload: on
    - cgi_path: [.py, /usr/bin/python3]
    - cgi_path: [.sh, /usr/bin/bash]
    - cgi_path: [.php, /usr/bin/php-cgi]
    - proxy_read_time_out: 10s
